### PR TITLE
feat: Added touchbar support on Mac

### PR DESCRIPTION
**Pull request by Morpa**
I added support for the Mac touchbar. For now I just added the option to create a new connection. In the future we can add something more.

### CODE REVIEW

**Comment by diego3g** [comment]
Hello @Morpa, thanks for the contribution. 

I think we should not keep these TouchBar config inside the `main.ts` file from electron, maybe we could create a TouchBarConfig.ts and import it inside the main, what do you think?

Also i think that `set-modal` is maybe ambiguous, maybe we can use something more descriptive like `open-new-connection-modal`.

**Comment by Morpa** [comment]
Hi,@diego3g  I really thought it was a good idea. I'll make the changes here and send it to you.

**Comment by Morpa** [comment]
@diego3g I researched the way you pointed out, but I did not find any satisfactory solution. I don't have much experience with React and Electron. In case you find something about, give me a touch.

**Comment by diego3g** [comment]
Closing for now since there were no updates.

**Pull request closed without merging**
