### PR TITLE
A better .gitignore

### PR DESCRIPTION
**Pull request by Muurilo**

### CODE REVIEW

**Comment by filliperomero** [comment]
I think you can change this file a litle bit since there are some files that you are ignoring and that will never exist in the project.

**Comment by Muurilo** [comment]
I know that I just put the default gitignore, I will remove the unnecessary ones @filliperomero

**Comment by diego3g** [comment]
We need to ignore the dist folder. Can you add it?

**Comment by Muurilo** [comment]
Done!

**Pull request merged**
