### PR TITLE
Feature/commitlint config

### PR DESCRIPTION
**Pull request by leoferreiralima**
Add CommitLint to ensure good commit messages
This PR depends of husky config in the  [PR#16](https://github.com/diego3g/rocketredis/pull/16)

### CODE REVIEW

**Comment by diego3g** [comment]
Can you take a look at diego3g/electron-typescript-react#11 to see if there is something we can bring to the repo too? It would be great to have matching config between these two repos.

**Comment by leoferreiralima** [comment]
yes, i will take a look

**Comment by leoferreiralima** [comment]
I made the pull request [diego3g/electron-typescript-react#11](https://github.com/diego3g/electron-typescript-react/pull/13) to keep a common config,can you take a look?

**Comment by diego3g** [comment]
Can you merge all these commits into a single one? You can use the rebase method

**Comment by diego3g** [comment]
I think you misunderstood what i said, you need to merge the commits into a single one but keep the message descriptive :smile: Can you change the commit message to something like:
```
chore: Add commit linting
```

**Comment by leoferreiralima** [comment]
> I think you misunderstood what i said, you need to merge the commits into a single one but keep the message descriptive 😄 Can you change the commit message to something like:
> 
> ```
> chore: Add commit linting
> ```

yes i will rewrite a new message more descritive as possible

**Comment by leoferreiralima** [comment]
@diego3g i thinks its all right now,if you need i change something more tell me

**Pull request merged**
