### PR TITLE
Add todo list on README

### PR DESCRIPTION
**Pull request by AlefeChorna**
We need a todo list so that we can know which tasks are pending

@diego3g Could you list some features?

### CODE REVIEW

**Comment by diego3g** [comment]
I think we should keep this inside a project here inside github instead of the README, what do you think?

**Comment by Muurilo** [comment]
It would be good to put the application design for us to develop.

**Comment by diego3g** [comment]
@Muurilo currently i don't have it, i was developing without any design. i'll try to design something.

**Comment by AlefeChorna** [comment]
> I think we should keep this inside a project here inside github instead of the README, what do you think?

great, but i don't have permission. Can you create?

**Comment by abdalla** [comment]
I would like to share my 2 cents, using project instead readme is way more useful, cuz we avoid 2 or more contributor developing the same feature.

**Comment by AlefeChorna** [comment]
> I would like to share my 2 cents, using project instead readme is way more useful, cuz we avoid 2 or more contributor developing the same feature.

A [github project](https://github.com/features/project-management) also solves this problem, in addition you could use a Kanban board and have control of tasks that are in development, completed, etc ...

**Comment by diego3g** [comment]
I'll create that tomorrow and then i send here and close the issue.

**Comment by diego3g** [comment]
I started designing the Rocket Redis UI inside Figma today (https://www.figma.com/file/YRor24p0TmTxcjl5L86jGb/Rocket-Redis?node-id=0%3A1), i'll try to get it done until tomorrow. I'll close this PR for now. Today i'll also create the project here inside Github with every task.

**Pull request closed without merging**
